language: android

notifications:
  email: false

env:
  global:
    - ANDROID_SDK_VERSION="r21.1.2"
    
before_install:
  - echo ">>>>>>>>>>>>$ANDROID_HOME"
# manually set sdk.dir variable, according to local paths
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
